# Generated by Django 5.0.6 on 2026-06-11 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.IntegerField(blank=True, null=True)),
                ('anxiety_level', models.IntegerField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('sleep_hours', models.IntegerField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('exercise_level', models.IntegerField(blank=True, null=True)),
                ('diet_quality', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('alcohol_caffeine_consumption', models.CharField(blank=True, max_length=255)),
                ('social_connection', models.IntegerField(blank=True, null=True)),
                ('social_interactions_quality', models.IntegerField(blank=True, null=True)),
                ('sense_of_meaning', models.IntegerField(blank=True, null=True)),
                ('felt_like_myself', models.IntegerField(blank=True, null=True)),
                ('environment_quality', models.IntegerField(blank=True, null=True)),
                ('overall_day_rating', models.IntegerField(blank=True, null=True)),
                ('best_thing_today', models.TextField(blank=True)),
                ('hardest_thing_today', models.TextField(blank=True)),
                ('significant_events', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-date'],
            },
        ),
    ]
