# Generated by Django 5.0.6 on 2024-06-29 07:16

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('log', wagtail.fields.RichTextField()),
                ('mood', models.IntegerField()),
                ('depression_level', models.IntegerField()),
                ('anxiety_level', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('sleep_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sleep_quality', models.IntegerField()),
                ('energy_level', models.IntegerField()),
                ('social_interactions_quality', models.IntegerField()),
                ('productivity_level', models.IntegerField()),
                ('diet_quality', models.IntegerField()),
                ('alcohol_caffeine_consumption', models.CharField(blank=True, max_length=255)),
                ('self_care_effectiveness', models.IntegerField()),
                ('significant_events', models.TextField(blank=True)),
                ('overall_day_rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
