# Generated by Django 5.0.6 on 2024-06-29 14:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_journalentry_date'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'journal entries'},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='diet_quality',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='productivity_level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='sleep_hours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='sleep_quality',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='social_interactions_quality',
            field=models.IntegerField(blank=True),
        ),
    ]
