# Generated by Django 5.0.6 on 2024-06-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_homepage_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the hero image', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
