# Generated by Django 5.0.6 on 2024-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_journalentryformpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='log',
            field=models.TextField(),
        ),
    ]
