# Generated by Django 5.0.6 on 2024-07-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_journalentry_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='alcohol_caffeine_consumption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='diet_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='productivity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='significant_events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='sleep_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='sleep_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='social_interactions_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
