# Generated by Django 5.0.6 on 2024-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_alter_journalentry_alcohol_caffeine_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='generated_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
