# Generated by Django 5.0.6 on 2024-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_journalentrypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
