# Generated by Django 5.0.6 on 2024-07-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_journalentry_entry_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
