# Generated by Django 5.0.6 on 2026-06-11 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_summarypage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentrypage',
            name='journal_entry',
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='alcohol_caffeine_consumption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='anxiety_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='depression_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='diet_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='energy_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='generated_header',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='mood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='overall_day_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='productivity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='self_care_effectiveness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='significant_events',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='sleep_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='sleep_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='social_interactions_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='stress_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
