# Generated by Django 5.0.6 on 2026-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_remove_journalentrypage_journal_entry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentrypage',
            old_name='depression_level',
            new_name='environment_quality',
        ),
        migrations.RenameField(
            model_name='journalentrypage',
            old_name='productivity_level',
            new_name='exercise_level',
        ),
        migrations.RenameField(
            model_name='journalentrypage',
            old_name='self_care_effectiveness',
            new_name='felt_like_myself',
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='best_thing_today',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='hardest_thing_today',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='sense_of_meaning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentrypage',
            name='social_connection',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
